### ISSUE TITLE
Curious on Price Oracle

### ISSUE THREAD

**Issue by PatrickAlphaC** [split-fi/split#62]
Hi Team! Just came across your project and am curious how you got your price oracle. Were you using the Chainlink price feeds to get your BAT/USD? https://docs.chain.link/docs/get-the-latest-price

**Comment by fragosti** [comment]
@PatrickAlphaC we actually don't use any USD price feeds, just cBAT/BAT is required in your example, which is simply provided by Compound https://compound.finance/docs/ctokens#exchange-rate

**Comment by PatrickAlphaC** [comment]
Ah I see, thanks for the information. Did that make you nervous for flash loan attacks? Or were liquidity attacks not a big concern for this hackathon project.
